### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by icculus** [libsdl-org/setup-sdl#10]
Can we either put this code under the zlib license, like the rest of SDL, or make it explicitly public domain?

**Comment by madebr** [comment]
I ran `license-checker` on the repo and got this:
```
$ npx license-checker --summary
├─ MIT: 421
├─ ISC: 36
├─ Apache-2.0: 15
├─ BSD-3-Clause: 15
├─ BSD-2-Clause: 13
├─ 0BSD: 2
├─ (MIT OR CC0-1.0): 2
├─ Python-2.0: 1
├─ MPL-2.0: 1
├─ CC-BY-4.0: 1
└─ CC0-1.0: 1
```
Welcome to npm hell :smiling_imp: 

I think it makes most sense to explicitly license the code public domain.
We want this code to be copied and adopted as much as possible.
The code lives independent from SDL, so we don't need to worry about incompatibilities

**Comment by icculus** [comment]
> Welcome to npm hell 😈

Gosh!

Ok, public domain it is. I'll stick a LICENSE.txt in here.

**Comment by madebr** [comment]
Thanks! Fixed in https://github.com/libsdl-org/setup-sdl/commit/6f40a743571624d3875a542911406fe32ef165c7
