### ISSUE TITLE
Primary branch should be "main"

### ISSUE THREAD

**Issue by icculus** [libsdl-org/setup-sdl#11]
Lots of people have different feelings about the primary branch being called "master," but everything else under libsdl-org is using "main" ... do you mind if I change it to match, before people start using this heavily, since this could start getting hardcoded in lots of projects before too long?

**Comment by madebr** [comment]
That's no problem for me.

**Comment by icculus** [comment]
Okay, changing it now.

**Comment by icculus** [comment]
```
 If you have a local clone, you can update it by running the following commands.

git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
