### ISSUE TITLE
Default to debug builds?

### ISSUE THREAD

**Issue by icculus** [libsdl-org/setup-sdl#14]
the `build-type` defaults to "Release", but this adds literally minutes onto an uncached build, at least on the Windows VMs. Since the primary goal is to get something one can link a third-party app against, maybe we should default to "Debug" so it's roughly the same result but compiles faster?

**Comment by madebr** [comment]
That's okay for me.
I didn't realize optimizations were costing this many cpu cycles.

**Comment by madebr** [comment]
Fixed in https://github.com/libsdl-org/setup-sdl/commit/446a4b76b47e58555678bc64c81f7db91e9f7209
