### ISSUE TITLE
Tag v1?

### ISSUE THREAD

**Issue by icculus** [libsdl-org/setup-sdl#17]
Are we at a safe point to tag v1 for this?

**Comment by madebr** [comment]
I think so. We're probably missing a lot of features for external projects, but luckily the natural number range is huge :P

**Comment by madebr** [comment]
I added a README, can you give it a proofread (and fix it also)?

**Comment by icculus** [comment]
It looks good to me. Tag when ready, and we'll announce it to the world.

**Comment by madebr** [comment]
I tagged `v1` and `v1.0.0`: seems like [actions/checkout](https://github.com/actions/checkout) adds new `v$x.$y.$z` tags and force pushes `v$x` tags.

I cannot publish the action on the GitHub marketplace. Somebody from the libsdl org needs to do that.
See https://github.com/libsdl-org/setup-sdl/releases/new?marketplace=true

**Comment by icculus** [comment]
To publish this on the marketplace, even as free software, libsdl-org has to accept a license agreement; it looks like pretty harmless boilerplate stuff ("don't do bad things, GitHub can use things published to the Marketplace", etc), but I'm pinging @slouken before anyone clicks Accept on it, since it applies to the organization and not me.

There's a link to view/accept it at the ["publish a release" link](https://github.com/libsdl-org/setup-sdl/releases/new?marketplace=true).

**Comment by slouken** [comment]
It looks good to me, but there's a lot to review, and I'm not a lawyer. I'll review it later and sign it once I've reviewed it.

One of the things I noticed off the bat is that it suggests a license specifically associated with the software published. Do we have one for this?

**Comment by madebr** [comment]
I don't know what text you're currently looking at, but perhaps it's talking about license of the action vs license of the software the action is installing?
For setup-sdl, this is "public domain" for setup-sdl, and zlib for SDL2/3.

**Comment by slouken** [comment]
I went head and agreed to the marketplace agreement. Feel free to publish this whenever you're ready.

**Comment by icculus** [comment]
This is live! https://github.com/libsdl-org/setup-sdl/releases/tag/v1

**Comment by slouken** [comment]
Can we use this to create SDL.xcframework on macOS? I'd love to not include that in the satellite libraries :)

**Comment by madebr** [comment]
For ci, you don't need to add any binaries or non-cmake project files to the satellite libraries: if SDL's cmake scipt can do it, this action can provide it.

The SDL cmake script knows how to create ordinary mac frameworks (please test this, I don't know what pList's are).
Building cmake SDL for the apple wearables is currently not tested (on ci).
