### ISSUE TITLE
Issue on Windows & MacOS: SDL2 isn't actually installed into anywhere CMake can find it

### ISSUE THREAD

**Issue by ProjectHSI** [libsdl-org/setup-sdl#24]
Not tied into the Linux error.

The action succeeds and lets the workflow continue, but configuring CMake causes a generic error about CMake not being able to find SDL2Config.cmake.

**Comment by madebr** [comment]
This action sets `SDL2_ROOT` environment variables which CMake should pick up.

Does this faq help?
https://github.com/libsdl-org/setup-sdl#faq
It has a few suggestions for older CMake versions (or scripts that use an older `cmake_minimum_required`)

When your project uses a custom `FindSDL2.cmake`, you might have to pass additional CMake arguments.


I test setup-sdl with this repo: https://github.com/madebr/setup-sdl-test
(Building SDL satellite libraries is not fully supported yet)

**Comment by ProjectHSI** [comment]
Hi there; sorry for the late reply.
I'm bumping the CMake minimum required version as for some reason default CMake projects in VS 2022 use a min version of 3.8... No idea why.

**Comment by ProjectHSI** [comment]
That fixed it, thanks.

**Comment by ProjectHSI** [comment]
(closed as not planned due to it being an issue with my end, not setup-sdl.)
