### ISSUE TITLE
Windows builds failing with sdl3-latest

### ISSUE THREAD

**Issue by icculus** [libsdl-org/setup-sdl#27]
Can't find "gameinput.h" for some Windows GDK thing...

https://github.com/icculus/DirkSimple/actions/runs/12128890658/job/33816371281

sdl2-latest works fine (or was working fine when this ran 2 days ago, at least).

.yml for the run is here: https://github.com/icculus/DirkSimple/blob/15028f2b63bb15c29feabd8df1224b8833bf354b/.github/workflows/main.yml

**Comment by madebr** [comment]
This has been reported on SDL at https://github.com/libsdl-org/SDL/issues/11487

I don't understand how CMake configure succeeds, but fails at build time.
https://github.com/libsdl-org/SDL/issues/11487#issuecomment-2487405649
Your logs show the same thing.

**Comment by madebr** [comment]
https://github.com/actions/runner-images/issues/10980#issuecomment-2513163023

> I think there's something wrong with either the MSBuild files or the CMake Visual Studio generator on the runner image.
Switching to the Ninja CMake generator does not cause a gameinput.h error.

**Comment by madebr** [comment]
See https://github.com/icculus/DirkSimple/pull/32 for the DirkSimple fix.

**Comment by learn-more** [comment]
Selecting an older sdk also works, for cmake this would be something like replacing 
```bash
cmake -Bbuild -T v143 -A ${{ matrix.platform }}
```
with
```bash
cmake -Bbuild -T v143 -A ${{ matrix.platform }},version=10.0.26100.0
```

**Comment by 1vanK** [comment]
> Selecting an older sdk also works, for cmake this would be something like replacing

26100 is latest SDK: https://github.com/actions/runner-images/blob/win22/20241201.2/images/windows/Windows2022-Readme.md
