### ISSUE TITLE
SDL versions are hardcoded in src/constants.ts

### ISSUE THREAD

**Issue by madebr** [libsdl-org/setup-sdl#5]
For now, all SDL releases are hardcoded in [`src/constants.ts`](https://github.com/madebr/setup-sdl/blob/0f04e1ac64b9bc272cfd40f7ee3fffed173153b8/src/constants.ts#L5-L42).
This means this repo needs an update after every SDL release.

Perhaps some GitHub api could be used to fetch all available releases?

**Comment by madebr** [comment]
The list is probably also too long since not all versions have good CMake support.

**Comment by slouken** [comment]
FYI, we have release-2.28.0 now. :)

**Comment by slouken** [comment]
We don't have a 3.0 pre-release, there's just main.

**Comment by madebr** [comment]
I meant this thag: https://github.com/libsdl-org/SDL/tree/prerelease-3.0.0.
Looks like it is still there (I thought it was removed because it was not visible in the output of `gh release list -R libsdl-or^CSDL -L 1000`.

**Comment by slouken** [comment]
Oh, you shouldn't use that tag. It doesn't correspond to anything useful.

**Comment by madebr** [comment]
Versions are not embedded anymore since https://github.com/libsdl-org/setup-sdl/commit/f209f602ccff9007193bc3e685e22fa75ff2aa27
